import type { Asset_Category, Asset_Sub_Category } from "@/data/types";
import type { Asset } from "@/data/types";

export const asset_categories: Asset_Category[] = [
  {
    category_id: 1,
    category_name: "Internal",
  },
  {
    category_id: 2,
    category_name: "External",
  },
];

export const asset_sub_categories: Asset_Sub_Category[] = [
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 1,
    sub_category_name: "Laptop",
    code: "LP-1231",
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 2,
    sub_category_name: "Network",
    code: "NT-1232",
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 3,
    sub_category_name: "Router",
    code: "RT-1231",
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 4,
    sub_category_name: "Cables",
    code: "CB-1232",
  },
];

export const asset_testcases: Asset[] = [
  {
    asset_id: 1,
    asset_name: "Dell Latitude 5420",
    category_id: 1,
    sub_category_id: 1,
    asset_condition_id: 1,
    location: "HQ Room 101",
    status_id: 1,
    serial_number: "DL5420-001",
    brand: "Dell",
    specifications: "Intel i5, 16GB RAM, 512GB SSD",
    asset_amount: 1200,
    warranty_duration: 24,
    warranty_due_date: "2026-09-19",
    purchase_date: "2024-09-19",
    notes: "Assigned to IT",
    type_id: 1,
    file: "dell_latitude_5420.pdf",
    insurance_id: "INS-001",
  },
  {
    asset_id: 2,
    asset_name: "HP EliteBook 840",
    category_id: 1,
    sub_category_id: 1,
    asset_condition_id: 1,
    location: "HQ Room 102",
    status_id: 2,
    serial_number: "HP840-002",
    brand: "HP",
    specifications: "Intel i7, 16GB RAM, 1TB SSD",
    asset_amount: 1400,
    warranty_duration: 36,
    warranty_due_date: "2027-09-19",
    purchase_date: "2024-03-15",
    notes: "Spare laptop",
    type_id: 1,
    file: "hp_elitebook_840.pdf",
    insurance_id: "INS-002",
  },
  {
    asset_id: 3,
    asset_name: "Cisco Catalyst Switch",
    category_id: 1,
    sub_category_id: 2,
    asset_condition_id: 2,
    location: "Server Room",
    status_id: 1,
    serial_number: "CISCO-SW-003",
    brand: "Cisco",
    specifications: "48-port, PoE+",
    asset_amount: 2500,
    warranty_duration: 36,
    warranty_due_date: "2028-01-01",
    purchase_date: "2025-01-01",
    notes: "Core switch",
    type_id: 2,
    file: "cisco_switch.pdf",
    insurance_id: "INS-003",
  },
  {
    asset_id: 4,
    asset_name: "Ubiquiti EdgeRouter",
    category_id: 2,
    sub_category_id: 3,
    asset_condition_id: 1,
    location: "Branch Office",
    status_id: 1,
    serial_number: "UBI-ER-004",
    brand: "Ubiquiti",
    specifications: "8-port, Gigabit",
    asset_amount: 600,
    warranty_duration: 12,
    warranty_due_date: "2026-09-19",
    purchase_date: "2025-09-19",
    notes: "Branch router",
    type_id: 3,
    file: "ubiquiti_edgerouter.pdf",
    insurance_id: "INS-004",
  },
  {
    asset_id: 5,
    asset_name: "TP-Link Network Cable",
    category_id: 2,
    sub_category_id: 4,
    asset_condition_id: 1,
    location: "HQ Storage",
    status_id: 1,
    serial_number: "TPL-CB-005",
    brand: "TP-Link",
    specifications: "Cat6, 100m",
    asset_amount: 80,
    warranty_duration: 6,
    warranty_due_date: "2026-03-19",
    purchase_date: "2025-09-19",
    notes: "Spare cable",
    type_id: 4,
    file: "tplink_cable.pdf",
    insurance_id: "INS-005",
  },
  {
    asset_id: 6,
    asset_name: "Lenovo ThinkPad X1",
    category_id: 1,
    sub_category_id: 1,
    asset_condition_id: 2,
    location: "HQ Room 103",
    status_id: 2,
    serial_number: "LEN-X1-006",
    brand: "Lenovo",
    specifications: "Intel i7, 32GB RAM, 1TB SSD",
    asset_amount: 1800,
    warranty_duration: 24,
    warranty_due_date: "2027-09-19",
    purchase_date: "2025-09-19",
    notes: "Loaned to staff",
    type_id: 1,
    file: "lenovo_thinkpad_x1.pdf",
    insurance_id: "INS-006",
  },
  {
    asset_id: 7,
    asset_name: "Aruba Network Switch",
    category_id: 1,
    sub_category_id: 2,
    asset_condition_id: 1,
    location: "HQ Network Closet",
    status_id: 1,
    serial_number: "ARUBA-SW-007",
    brand: "Aruba",
    specifications: "24-port, PoE",
    asset_amount: 1200,
    warranty_duration: 36,
    warranty_due_date: "2028-09-19",
    purchase_date: "2025-09-19",
    notes: "Edge switch",
    type_id: 2,
    file: "aruba_switch.pdf",
    insurance_id: "INS-007",
  },
  {
    asset_id: 8,
    asset_name: "Netgear Router",
    category_id: 2,
    sub_category_id: 3,
    asset_condition_id: 2,
    location: "Remote Site",
    status_id: 2,
    serial_number: "NET-RT-008",
    brand: "Netgear",
    specifications: "Dual-band, 4-port",
    asset_amount: 300,
    warranty_duration: 12,
    warranty_due_date: "2026-09-19",
    purchase_date: "2025-09-19",
    notes: "Backup router",
    type_id: 3,
    file: "netgear_router.pdf",
    insurance_id: "INS-008",
  },
  {
    asset_id: 9,
    asset_name: "Belkin Patch Cable",
    category_id: 2,
    sub_category_id: 4,
    asset_condition_id: 1,
    location: "HQ Storage",
    status_id: 1,
    serial_number: "BELKIN-CB-009",
    brand: "Belkin",
    specifications: "Cat5e, 10m",
    asset_amount: 20,
    warranty_duration: 6,
    warranty_due_date: "2026-03-19",
    purchase_date: "2025-09-19",
    notes: "Short cable",
    type_id: 4,
    file: "belkin_patch_cable.pdf",
    insurance_id: "INS-009",
  },
  {
    asset_id: 10,
    asset_name: "Apple MacBook Pro",
    category_id: 1,
    sub_category_id: 1,
    asset_condition_id: 1,
    location: "HQ Room 104",
    status_id: 1,
    serial_number: "MBP-010",
    brand: "Apple",
    specifications: "M1 Pro, 16GB RAM, 1TB SSD",
    asset_amount: 2200,
    warranty_duration: 24,
    warranty_due_date: "2027-09-19",
    purchase_date: "2025-09-19",
    notes: "Design team",
    type_id: 1,
    file: "macbook_pro.pdf",
    insurance_id: "INS-010",
  },
];
