import type {
  Asset_Category,
  Asset_Sub_Category,
  Asset_Type,
  Insurance,
} from "@/data/types";

export const asset_categories: Asset_Category[] = [
  {
    category_id: 1,
    category_name: "Internal",
  },
  {
    category_id: 2,
    category_name: "External",
  },
  {
    category_id: 3,
    category_name: "Events",
  },
];

export const asset_sub_categories: Asset_Sub_Category[] = [
  {
    sub_category_id: 1,
    sub_category_name: "Laptop",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "LAP",
  },
  {
    sub_category_id: 2,
    sub_category_name: "Desktop",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "DSK",
  },
  {
    sub_category_id: 3,
    sub_category_name: "Tablet",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "TAB",
  },
  {
    sub_category_id: 4,
    sub_category_name: "Mobile Phone",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "MOB",
  },
  {
    sub_category_id: 5,
    sub_category_name: "Monitor",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "MON",
  },
  {
    sub_category_id: 6,
    sub_category_name: "Printer",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "PRT",
  },
  {
    sub_category_id: 7,
    sub_category_name: "Scanner",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "SCN",
  },
  {
    sub_category_id: 8,
    sub_category_name: "Projector",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "PRJ",
  },
  {
    sub_category_id: 9,
    sub_category_name: "Network Equipment",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "NET",
  },
  {
    sub_category_id: 10,
    sub_category_name: "Server",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "SRV",
  },
  {
    sub_category_id: 11,
    sub_category_name: "Security Camera",
    category_id: 2, // External
    category_name: "External",
    code: "CAM",
  },
  {
    sub_category_id: 12,
    sub_category_name: "Access Control",
    category_id: 2, // External
    category_name: "External",
    code: "ACC",
  },
  {
    sub_category_id: 13,
    sub_category_name: "Furniture",
    category_id: 2, // External
    category_name: "External",
    code: "FUR",
  },
  {
    sub_category_id: 14,
    sub_category_name: "Vehicle",
    category_id: 2, // External
    category_name: "External",
    code: "VEH",
  },
  {
    sub_category_id: 15,
    sub_category_name: "Tools & Equipment",
    category_id: 2, // External
    category_name: "External",
    code: "TLE",
  },
  {
    sub_category_id: 16,
    sub_category_name: "Event Equipment",
    category_id: 3, // Events
    category_name: "Events",
    code: "EVT",
  },
  {
    sub_category_id: 17,
    sub_category_name: "Audio Visual",
    category_id: 3, // Events
    category_name: "Events",
    code: "AV",
  },
  {
    sub_category_id: 18,
    sub_category_name: "Lighting",
    category_id: 3, // Events
    category_name: "Events",
    code: "LGT",
  },
];

export const asset_types: Asset_Type[] = [
  // Laptop Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 1,
    sub_category_name: "Laptop",
    code: "LAP",
    type_id: 1,
    type_name: "Business Laptop",
    type_code: 101,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 1,
    sub_category_name: "Laptop",
    code: "LAP",
    type_id: 2,
    type_name: "Gaming Laptop",
    type_code: 102,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 1,
    sub_category_name: "Laptop",
    code: "LAP",
    type_id: 3,
    type_name: "Ultrabook",
    type_code: 103,
  },
  // Desktop Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 2,
    sub_category_name: "Desktop",
    code: "DSK",
    type_id: 4,
    type_name: "Workstation",
    type_code: 201,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 2,
    sub_category_name: "Desktop",
    code: "DSK",
    type_id: 5,
    type_name: "Mini PC",
    type_code: 202,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 2,
    sub_category_name: "Desktop",
    code: "DSK",
    type_id: 6,
    type_name: "All-in-One PC",
    type_code: 203,
  },
  // Tablet Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 3,
    sub_category_name: "Tablet",
    code: "TAB",
    type_id: 7,
    type_name: "iPad",
    type_code: 301,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 3,
    sub_category_name: "Tablet",
    code: "TAB",
    type_id: 8,
    type_name: "Android Tablet",
    type_code: 302,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 3,
    sub_category_name: "Tablet",
    code: "TAB",
    type_id: 9,
    type_name: "Surface Tablet",
    type_code: 303,
  },
  // Mobile Phone Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 4,
    sub_category_name: "Mobile Phone",
    code: "MOB",
    type_id: 10,
    type_name: "iPhone",
    type_code: 401,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 4,
    sub_category_name: "Mobile Phone",
    code: "MOB",
    type_id: 11,
    type_name: "Android Phone",
    type_code: 402,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 4,
    sub_category_name: "Mobile Phone",
    code: "MOB",
    type_id: 12,
    type_name: "Feature Phone",
    type_code: 403,
  },
  // Monitor Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 5,
    sub_category_name: "Monitor",
    code: "MON",
    type_id: 13,
    type_name: "LED Monitor",
    type_code: 501,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 5,
    sub_category_name: "Monitor",
    code: "MON",
    type_id: 14,
    type_name: "OLED Monitor",
    type_code: 502,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 5,
    sub_category_name: "Monitor",
    code: "MON",
    type_id: 15,
    type_name: "4K Monitor",
    type_code: 503,
  },
  // Printer Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 6,
    sub_category_name: "Printer",
    code: "PRT",
    type_id: 16,
    type_name: "Laser Printer",
    type_code: 601,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 6,
    sub_category_name: "Printer",
    code: "PRT",
    type_id: 17,
    type_name: "Inkjet Printer",
    type_code: 602,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 6,
    sub_category_name: "Printer",
    code: "PRT",
    type_id: 18,
    type_name: "3D Printer",
    type_code: 603,
  },
  // Network Equipment Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 9,
    sub_category_name: "Network Equipment",
    code: "NET",
    type_id: 19,
    type_name: "Router",
    type_code: 901,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 9,
    sub_category_name: "Network Equipment",
    code: "NET",
    type_id: 20,
    type_name: "Switch",
    type_code: 902,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 9,
    sub_category_name: "Network Equipment",
    code: "NET",
    type_id: 21,
    type_name: "Access Point",
    type_code: 903,
  },
  // Server Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 10,
    sub_category_name: "Server",
    code: "SRV",
    type_id: 22,
    type_name: "Rack Server",
    type_code: 1001,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 10,
    sub_category_name: "Server",
    code: "SRV",
    type_id: 23,
    type_name: "Blade Server",
    type_code: 1002,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 10,
    sub_category_name: "Server",
    code: "SRV",
    type_id: 24,
    type_name: "Tower Server",
    type_code: 1003,
  },
  // Security Camera Types
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 11,
    sub_category_name: "Security Camera",
    code: "CAM",
    type_id: 25,
    type_name: "IP Camera",
    type_code: 1101,
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 11,
    sub_category_name: "Security Camera",
    code: "CAM",
    type_id: 26,
    type_name: "PTZ Camera",
    type_code: 1102,
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 11,
    sub_category_name: "Security Camera",
    code: "CAM",
    type_id: 27,
    type_name: "Dome Camera",
    type_code: 1103,
  },
  // Vehicle Types
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 14,
    sub_category_name: "Vehicle",
    code: "VEH",
    type_id: 28,
    type_name: "Company Car",
    type_code: 1401,
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 14,
    sub_category_name: "Vehicle",
    code: "VEH",
    type_id: 29,
    type_name: "Van",
    type_code: 1402,
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 14,
    sub_category_name: "Vehicle",
    code: "VEH",
    type_id: 30,
    type_name: "Motorcycle",
    type_code: 1403,
  },
  // Event Equipment Types
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 16,
    sub_category_name: "Event Equipment",
    code: "EVT",
    type_id: 31,
    type_name: "Stage Platform",
    type_code: 1601,
  },
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 16,
    sub_category_name: "Event Equipment",
    code: "EVT",
    type_id: 32,
    type_name: "Tent",
    type_code: 1602,
  },
  // Audio Visual Types
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 17,
    sub_category_name: "Audio Visual",
    code: "AV",
    type_id: 33,
    type_name: "Projector",
    type_code: 1701,
  },
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 17,
    sub_category_name: "Audio Visual",
    code: "AV",
    type_id: 34,
    type_name: "PA System",
    type_code: 1702,
  },
  // Lighting Types
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 18,
    sub_category_name: "Lighting",
    code: "LGT",
    type_id: 35,
    type_name: "LED Lighting Rig",
    type_code: 1801,
  },
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 18,
    sub_category_name: "Lighting",
    code: "LGT",
    type_id: 36,
    type_name: "Spotlight",
    type_code: 1802,
  },
];

export const asset_conditions = [
  { asset_condition_id: 1, asset_condition_name: "Excellent" },
  { asset_condition_id: 2, asset_condition_name: "Good" },
  { asset_condition_id: 3, asset_condition_name: "Fair" },
  { asset_condition_id: 4, asset_condition_name: "Poor" },
  { asset_condition_id: 5, asset_condition_name: "Needs Repair" },
  { asset_condition_id: 6, asset_condition_name: "Out of Service" },
  { asset_condition_id: 7, asset_condition_name: "Under Maintenance" },
  { asset_condition_id: 8, asset_condition_name: "Damaged" },
];

export const insurances: Insurance[] = [
  {
    insurance_id: 1,
    insurance_name: "TechGuard Insurance",
    insurance_desc:
      "Comprehensive coverage for technology assets including laptops, tablets, and mobile devices",
    coverage: 50000,
  },
  {
    insurance_id: 2,
    insurance_name: "Corporate Asset Shield",
    insurance_desc:
      "Protection against theft and accidental damage for all business equipment",
    coverage: 75000,
  },
  {
    insurance_id: 3,
    insurance_name: "Business Equipment Insurance",
    insurance_desc: "Specialized coverage for office equipment and peripherals",
    coverage: 30000,
  },
  {
    insurance_id: 4,
    insurance_name: "SecureAsset Insurance",
    insurance_desc:
      "Full coverage including replacement cost and business interruption",
    coverage: 100000,
  },
  {
    insurance_id: 5,
    insurance_name: "Global Tech Insurance",
    insurance_desc:
      "Electronics-specific coverage for high-value technology assets",
    coverage: 60000,
  },
  {
    insurance_id: 6,
    insurance_name: "Enterprise Equipment Protect",
    insurance_desc:
      "Combined liability and asset protection for enterprise-grade equipment",
    coverage: 80000,
  },
  {
    insurance_id: 7,
    insurance_name: "IT Asset Insurance",
    insurance_desc: "Technology-specific coverage with rapid replacement services",
    coverage: 45000,
  },
  {
    insurance_id: 8,
    insurance_name: "Universal Business Cover",
    insurance_desc:
      "All-risk coverage for business assets including natural disasters and cyber incidents",
    coverage: 90000,
  },
];

export const status = [
  {
    status_id: 1,
    status_name: "Available",
  },
  {
    status_id: 2,
    status_name: "In Use",
  },
  {
    status_id: 3,
    status_name: "Under Repair",
  },
  {
    status_id: 4,
    status_name: "Out of Service",
  },
  {
    status_id: 5,
    status_name: "Borrowed",
  },
  {
    status_id: 6,
    status_name: "Reserved",
  },
  {
    status_id: 7,
    status_name: "Pending Return",
  },
  {
    status_id: 8,
    status_name: "Maintenance",
  },
  {
    status_id: 9,
    status_name: "Disposed",
  },
  {
    status_id: 10,
    status_name: "Lost",
  },
  {
    status_id: 11,
    status_name: "Stolen",
  },
  {
    status_id: 12,
    status_name: "Retired",
  },
];

export const company_id = [
  {
    company_id: 1,
    company_name: "United Neon Advertising, Inc."
  },
  {
    company_id: 2,
    company_name: "Breakthrough Leadership Management Consultancy, Inc."
  },
  {
    company_id: 3,
    company_name: "InnovationOne Inc.",
  },
  {
    company_id: 4,
    company_name: "Inspire Leadership Consultancy Inc.",
  },
  {
    company_id: 8,
    company_name: "SeeWorthy International/LinkOD",
  },
  {
    company_id: 9,
    company_name: "TapAds Media Corp",
  },
  {
    company_id: 10,
    company_name: "United Neon Foundation Inc.",
  },
  {
    company_id: 11,
    company_name: "United Transit Ads System Inc.",
  },
  {
    company_id: 12,
    company_name: "Lighthouse Education Center",
  },
  {
    company_id: 13,
    company_name: "Ever Corporation",
  },
  {
    company_id: 14,
    company_name: "Gateway Bizads Inc.",
  },
]

export const departments = [
  { department_id: 1, department_name: "Information Technology" },
  { department_id: 2, department_name: "Human Resources" },
  { department_id: 3, department_name: "Finance and Accounting" },
  { department_id: 4, department_name: "Marketing and Communications" },
  { department_id: 5, department_name: "Operations Management" },
  { department_id: 6, department_name: "Sales and Business Development" },
  { department_id: 7, department_name: "Research and Development" },
  { department_id: 8, department_name: "Quality Assurance" },
  { department_id: 9, department_name: "Customer Service" },
  { department_id: 10, department_name: "Legal and Compliance" },
  { department_id: 11, department_name: "Procurement and Supply Chain" },
  { department_id: 12, department_name: "Project Management Office" },
  { department_id: 13, department_name: "Training and Development" },
  { department_id: 14, department_name: "Administration and Facilities" },
  { department_id: 15, department_name: "Security and Risk Management" },
  { department_id: 16, department_name: "Data Analytics and Business Intelligence" },
  { department_id: 17, department_name: "Corporate Strategy and Planning" },
  { department_id: 18, department_name: "Public Relations" },
  { department_id: 19, department_name: "Internal Audit" },
  { department_id: 20, department_name: "Environmental Health and Safety" },
  { department_id: 21, department_name: "Innovation and Digital Transformation" },
  { department_id: 22, department_name: "Executive Management" },
]

export const employees = [
  { employee_id: 1, employee_name: "Maria Santos" },
  { employee_id: 2, employee_name: "Juan Dela Cruz" },
  { employee_id: 3, employee_name: "Ana Garcia" },
  { employee_id: 4, employee_name: "Carlos Reyes" },
  { employee_id: 5, employee_name: "Isabella Rodriguez" },
  { employee_id: 6, employee_name: "Miguel Torres" },
  { employee_id: 7, employee_name: "Sofia Morales" },
  { employee_id: 8, employee_name: "Diego Hernandez" },
  { employee_id: 9, employee_name: "Carmen Flores" },
  { employee_id: 10, employee_name: "Rafael Castro" },
  { employee_id: 11, employee_name: "Lucia Mendoza" },
  { employee_id: 12, employee_name: "Antonio Ramos" },
  { employee_id: 13, employee_name: "Valentina Gutierrez" },
  { employee_id: 14, employee_name: "Fernando Silva" },
  { employee_id: 15, employee_name: "Gabriela Vargas" },
  { employee_id: 16, employee_name: "Ricardo Ortega" },
  { employee_id: 17, employee_name: "Camila Jimenez" },
  { employee_id: 18, employee_name: "Alejandro Perez" },
  { employee_id: 19, employee_name: "Natalia Aguilar" },
  { employee_id: 20, employee_name: "Emilio Navarro" },
  { employee_id: 21, employee_name: "Victoria Ruiz" },
  { employee_id: 22, employee_name: "Sebastian Medina" },
  { employee_id: 23, employee_name: "Adriana Campos" },
  { employee_id: 24, employee_name: "Mateo Sandoval" },
  { employee_id: 25, employee_name: "Daniela Vega" },
  { employee_id: 26, employee_name: "Leonardo Romero" },
  { employee_id: 27, employee_name: "Valeria Guerrero" },
  { employee_id: 28, employee_name: "Nicolas Herrera" },
  { employee_id: 29, employee_name: "Mariana Cruz" },
  { employee_id: 30, employee_name: "Joaquin Rivera" },
  { employee_id: 31, employee_name: "Regina Blanco" },
  { employee_id: 32, employee_name: "Andres Fuentes" },
  { employee_id: 33, employee_name: "Paola Soto" },
  { employee_id: 34, employee_name: "Gabriel Luna" },
  { employee_id: 35, employee_name: "Esperanza Delgado" },
  { employee_id: 36, employee_name: "Eduardo Contreras" },
  { employee_id: 37, employee_name: "Cristina Pacheco" },
  { employee_id: 38, employee_name: "Raul Espinoza" },
  { employee_id: 39, employee_name: "Beatriz Molina" },
  { employee_id: 40, employee_name: "Sergio Valdez" },
  { employee_id: 41, employee_name: "Alejandra Cabrera" },
  { employee_id: 42, employee_name: "Pablo Lozano" },
  { employee_id: 43, employee_name: "Fernanda Rojas" },
  { employee_id: 44, employee_name: "Ignacio Moreno" },
  { employee_id: 45, employee_name: "Ximena Castillo" },
  { employee_id: 46, employee_name: "Manuel Rosales" },
  { employee_id: 47, employee_name: "Cecilia Padilla" },
  { employee_id: 48, employee_name: "Rodrigo Salazar" },
  { employee_id: 49, employee_name: "Alicia Mendez" },
  { employee_id: 50, employee_name: "Esteban Nunez" },
  { employee_id: 51, employee_name: "Monica Acosta" },
  { employee_id: 52, employee_name: "Hector Rubio" },
  { employee_id: 53, employee_name: "Lorena Ibarra" },
  { employee_id: 54, employee_name: "Felipe Cuevas" },
  { employee_id: 55, employee_name: "Claudia Velasco" },
  { employee_id: 56, employee_name: "Victor Cordova" },
  { employee_id: 57, employee_name: "Sandra Maldonado" },
  { employee_id: 58, employee_name: "Armando Juarez" },
  { employee_id: 59, employee_name: "Patricia Dominguez" },
  { employee_id: 60, employee_name: "Arturo Villalobos" },
  { employee_id: 61, employee_name: "Elena Bautista" },
  { employee_id: 62, employee_name: "Mauricio Guereca" },
  { employee_id: 63, employee_name: "Rosa Estrada" },
  { employee_id: 64, employee_name: "Francisco Avalos" },
  { employee_id: 65, employee_name: "Silvia Carrillo" },
  { employee_id: 66, employee_name: "Enrique Ponce" },
  { employee_id: 67, employee_name: "Martha Cazares" },
  { employee_id: 68, employee_name: "Jorge Montes" },
  { employee_id: 69, employee_name: "Brenda Figueroa" },
  { employee_id: 70, employee_name: "Cesar Gamboa" },
  { employee_id: 71, employee_name: "Yolanda Quinones" },
  { employee_id: 72, employee_name: "Gustavo Santillan" },
  { employee_id: 73, employee_name: "Marisol Zarate" },
  { employee_id: 74, employee_name: "Omar Gallegos" },
  { employee_id: 75, employee_name: "Gloria Trejo" },
  { employee_id: 76, employee_name: "Ruben Esquivel" },
  { employee_id: 77, employee_name: "Susana Avila" },
  { employee_id: 78, employee_name: "Ivan Cardenas" },
  { employee_id: 79, employee_name: "Leticia Barrera" },
  { employee_id: 80, employee_name: "Alberto Cervantes" },
  { employee_id: 81, employee_name: "Teresa Montoya" },
  { employee_id: 82, employee_name: "Julio Arredondo" },
  { employee_id: 83, employee_name: "Angela Galvan" },
  { employee_id: 84, employee_name: "Luis Alarcon" },
  { employee_id: 85, employee_name: "Rocio Escobar" },
  { employee_id: 86, employee_name: "Jaime Villanueva" },
  { employee_id: 87, employee_name: "Irma Zamora" },
  { employee_id: 88, employee_name: "Alfredo Olvera" },
  { employee_id: 89, employee_name: "Graciela Herrera" },
  { employee_id: 90, employee_name: "Roberto Tapia" },
  { employee_id: 91, employee_name: "Olga Berrios" },
  { employee_id: 92, employee_name: "Gerardo Vazquez" },
  { employee_id: 93, employee_name: "Norma Alcala" },
  { employee_id: 94, employee_name: "Javier Miranda" },
  { employee_id: 95, employee_name: "Delia Serrano" },
  { employee_id: 96, employee_name: "Marco Ochoa" },
  { employee_id: 97, employee_name: "Amparo Lugo" },
  { employee_id: 98, employee_name: "Alfredo Bernal" },
  { employee_id: 99, employee_name: "Veronica Solis" },
  { employee_id: 100, employee_name: "Guillermo Paredes" },
]

export const urgency = [
  { urgency_id: 1, urgency_name: "Low" },
  { urgency_id: 2, urgency_name: "Medium" },
  { urgency_id: 3, urgency_name: "High" },
  { urgency_id: 4, urgency_name: "Critical" },
  { urgency_id: 5, urgency_name: "Emergency" },
]



