import type {
  Asset_Category,
  Asset_Sub_Category,
  Asset_Type,
  Company,
  Department,
  Employee,
  Insurance,
  Unit,
} from "@/data/types";

export const asset_categories: Asset_Category[] = [
  {
    category_id: 1,
    category_name: "Internal",
  },
  {
    category_id: 2,
    category_name: "External",
  },
  {
    category_id: 3,
    category_name: "Events",
  },
];

export const asset_sub_categories: Asset_Sub_Category[] = [
  {
    sub_category_id: 1,
    sub_category_name: "Laptop",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "LAP",
  },
  {
    sub_category_id: 2,
    sub_category_name: "Desktop",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "DSK",
  },
  {
    sub_category_id: 3,
    sub_category_name: "Tablet",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "TAB",
  },
  {
    sub_category_id: 4,
    sub_category_name: "Mobile Phone",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "MOB",
  },
  {
    sub_category_id: 5,
    sub_category_name: "Monitor",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "MON",
  },
  {
    sub_category_id: 6,
    sub_category_name: "Printer",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "PRT",
  },
  {
    sub_category_id: 7,
    sub_category_name: "Scanner",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "SCN",
  },
  {
    sub_category_id: 8,
    sub_category_name: "Projector",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "PRJ",
  },
  {
    sub_category_id: 9,
    sub_category_name: "Network Equipment",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "NET",
  },
  {
    sub_category_id: 10,
    sub_category_name: "Server",
    category_id: 1, // Internal
    category_name: "Internal",
    code: "SRV",
  },
  {
    sub_category_id: 11,
    sub_category_name: "Security Camera",
    category_id: 2, // External
    category_name: "External",
    code: "CAM",
  },
  {
    sub_category_id: 12,
    sub_category_name: "Access Control",
    category_id: 2, // External
    category_name: "External",
    code: "ACC",
  },
  {
    sub_category_id: 13,
    sub_category_name: "Furniture",
    category_id: 2, // External
    category_name: "External",
    code: "FUR",
  },
  {
    sub_category_id: 14,
    sub_category_name: "Vehicle",
    category_id: 2, // External
    category_name: "External",
    code: "VEH",
  },
  {
    sub_category_id: 15,
    sub_category_name: "Tools & Equipment",
    category_id: 2, // External
    category_name: "External",
    code: "TLE",
  },
  {
    sub_category_id: 16,
    sub_category_name: "Event Equipment",
    category_id: 3, // Events
    category_name: "Events",
    code: "EVT",
  },
  {
    sub_category_id: 17,
    sub_category_name: "Audio Visual",
    category_id: 3, // Events
    category_name: "Events",
    code: "AV",
  },
  {
    sub_category_id: 18,
    sub_category_name: "Lighting",
    category_id: 3, // Events
    category_name: "Events",
    code: "LGT",
  },
];

export const asset_types: Asset_Type[] = [
  // Laptop Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 1,
    sub_category_name: "Laptop",
    code: "LAP",
    type_id: 1,
    type_name: "Business Laptop",
    type_code: 101,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 1,
    sub_category_name: "Laptop",
    code: "LAP",
    type_id: 2,
    type_name: "Gaming Laptop",
    type_code: 102,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 1,
    sub_category_name: "Laptop",
    code: "LAP",
    type_id: 3,
    type_name: "Ultrabook",
    type_code: 103,
  },
  // Desktop Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 2,
    sub_category_name: "Desktop",
    code: "DSK",
    type_id: 4,
    type_name: "Workstation",
    type_code: 201,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 2,
    sub_category_name: "Desktop",
    code: "DSK",
    type_id: 5,
    type_name: "Mini PC",
    type_code: 202,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 2,
    sub_category_name: "Desktop",
    code: "DSK",
    type_id: 6,
    type_name: "All-in-One PC",
    type_code: 203,
  },
  // Tablet Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 3,
    sub_category_name: "Tablet",
    code: "TAB",
    type_id: 7,
    type_name: "iPad",
    type_code: 301,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 3,
    sub_category_name: "Tablet",
    code: "TAB",
    type_id: 8,
    type_name: "Android Tablet",
    type_code: 302,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 3,
    sub_category_name: "Tablet",
    code: "TAB",
    type_id: 9,
    type_name: "Surface Tablet",
    type_code: 303,
  },
  // Mobile Phone Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 4,
    sub_category_name: "Mobile Phone",
    code: "MOB",
    type_id: 10,
    type_name: "iPhone",
    type_code: 401,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 4,
    sub_category_name: "Mobile Phone",
    code: "MOB",
    type_id: 11,
    type_name: "Android Phone",
    type_code: 402,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 4,
    sub_category_name: "Mobile Phone",
    code: "MOB",
    type_id: 12,
    type_name: "Feature Phone",
    type_code: 403,
  },
  // Monitor Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 5,
    sub_category_name: "Monitor",
    code: "MON",
    type_id: 13,
    type_name: "LED Monitor",
    type_code: 501,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 5,
    sub_category_name: "Monitor",
    code: "MON",
    type_id: 14,
    type_name: "OLED Monitor",
    type_code: 502,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 5,
    sub_category_name: "Monitor",
    code: "MON",
    type_id: 15,
    type_name: "4K Monitor",
    type_code: 503,
  },
  // Printer Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 6,
    sub_category_name: "Printer",
    code: "PRT",
    type_id: 16,
    type_name: "Laser Printer",
    type_code: 601,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 6,
    sub_category_name: "Printer",
    code: "PRT",
    type_id: 17,
    type_name: "Inkjet Printer",
    type_code: 602,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 6,
    sub_category_name: "Printer",
    code: "PRT",
    type_id: 18,
    type_name: "3D Printer",
    type_code: 603,
  },
  // Network Equipment Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 9,
    sub_category_name: "Network Equipment",
    code: "NET",
    type_id: 19,
    type_name: "Router",
    type_code: 901,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 9,
    sub_category_name: "Network Equipment",
    code: "NET",
    type_id: 20,
    type_name: "Switch",
    type_code: 902,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 9,
    sub_category_name: "Network Equipment",
    code: "NET",
    type_id: 21,
    type_name: "Access Point",
    type_code: 903,
  },
  // Server Types
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 10,
    sub_category_name: "Server",
    code: "SRV",
    type_id: 22,
    type_name: "Rack Server",
    type_code: 1001,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 10,
    sub_category_name: "Server",
    code: "SRV",
    type_id: 23,
    type_name: "Blade Server",
    type_code: 1002,
  },
  {
    category_id: 1,
    category_name: "Internal",
    sub_category_id: 10,
    sub_category_name: "Server",
    code: "SRV",
    type_id: 24,
    type_name: "Tower Server",
    type_code: 1003,
  },
  // Security Camera Types
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 11,
    sub_category_name: "Security Camera",
    code: "CAM",
    type_id: 25,
    type_name: "IP Camera",
    type_code: 1101,
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 11,
    sub_category_name: "Security Camera",
    code: "CAM",
    type_id: 26,
    type_name: "PTZ Camera",
    type_code: 1102,
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 11,
    sub_category_name: "Security Camera",
    code: "CAM",
    type_id: 27,
    type_name: "Dome Camera",
    type_code: 1103,
  },
  // Vehicle Types
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 14,
    sub_category_name: "Vehicle",
    code: "VEH",
    type_id: 28,
    type_name: "Company Car",
    type_code: 1401,
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 14,
    sub_category_name: "Vehicle",
    code: "VEH",
    type_id: 29,
    type_name: "Van",
    type_code: 1402,
  },
  {
    category_id: 2,
    category_name: "External",
    sub_category_id: 14,
    sub_category_name: "Vehicle",
    code: "VEH",
    type_id: 30,
    type_name: "Motorcycle",
    type_code: 1403,
  },
  // Event Equipment Types
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 16,
    sub_category_name: "Event Equipment",
    code: "EVT",
    type_id: 31,
    type_name: "Stage Platform",
    type_code: 1601,
  },
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 16,
    sub_category_name: "Event Equipment",
    code: "EVT",
    type_id: 32,
    type_name: "Tent",
    type_code: 1602,
  },
  // Audio Visual Types
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 17,
    sub_category_name: "Audio Visual",
    code: "AV",
    type_id: 33,
    type_name: "Projector",
    type_code: 1701,
  },
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 17,
    sub_category_name: "Audio Visual",
    code: "AV",
    type_id: 34,
    type_name: "PA System",
    type_code: 1702,
  },
  // Lighting Types
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 18,
    sub_category_name: "Lighting",
    code: "LGT",
    type_id: 35,
    type_name: "LED Lighting Rig",
    type_code: 1801,
  },
  {
    category_id: 3,
    category_name: "Events",
    sub_category_id: 18,
    sub_category_name: "Lighting",
    code: "LGT",
    type_id: 36,
    type_name: "Spotlight",
    type_code: 1802,
  },
];

export const asset_conditions = [
  { asset_condition_id: 1, asset_condition_name: "Excellent" },
  { asset_condition_id: 2, asset_condition_name: "Good" },
  { asset_condition_id: 3, asset_condition_name: "Fair" },
  { asset_condition_id: 4, asset_condition_name: "Poor" },
  { asset_condition_id: 5, asset_condition_name: "Needs Repair" },
  { asset_condition_id: 6, asset_condition_name: "Out of Service" },
  { asset_condition_id: 7, asset_condition_name: "Under Maintenance" },
  { asset_condition_id: 8, asset_condition_name: "Damaged" },
];

export const insurances: Insurance[] = [
  {
    insurance_id: 1,
    insurance_name: "TechGuard Insurance",
    insurance_coverage:
      "Comprehensive coverage for technology assets including laptops, tablets, and mobile devices",
    insurance_date_from: new Date("2024-01-01"), // Fix: Convert to Date object
    insurance_date_to: new Date("2024-12-31"),   // Fix: Convert to Date object
  },
  {
    insurance_id: 2,
    insurance_name: "Corporate Asset Shield",
    insurance_coverage:
      "Protection against theft and accidental damage for all business equipment",
    insurance_date_from: new Date("2024-02-15"), // Fix: Convert to Date object
    insurance_date_to: new Date("2025-02-14"),   // Fix: Convert to Date object
  },
  {
    insurance_id: 3,
    insurance_name: "Business Equipment Insurance",
    insurance_coverage:
      "Specialized coverage for office equipment and peripherals",
    insurance_date_from: new Date("2024-03-01"), // Fix: Convert to Date object
    insurance_date_to: new Date("2025-02-28"),   // Fix: Convert to Date object
  },
  {
    insurance_id: 4,
    insurance_name: "SecureAsset Insurance",
    insurance_coverage:
      "Full coverage including replacement cost and business interruption",
    insurance_date_from: new Date("2024-01-15"), // Fix: Convert to Date object
    insurance_date_to: new Date("2025-01-14"),   // Fix: Convert to Date object
  },
  {
    insurance_id: 5,
    insurance_name: "Global Tech Insurance",
    insurance_coverage:
      "Electronics-specific coverage for high-value technology assets",
    insurance_date_from: new Date("2024-04-01"), // Fix: Convert to Date object
    insurance_date_to: new Date("2025-03-31"),   // Fix: Convert to Date object
  },
  {
    insurance_id: 6,
    insurance_name: "Enterprise Equipment Protect",
    insurance_coverage:
      "Combined liability and asset protection for enterprise-grade equipment",
    insurance_date_from: new Date("2024-05-01"), // Fix: Convert to Date object
    insurance_date_to: new Date("2025-04-30"),   // Fix: Convert to Date object
  },
  {
    insurance_id: 7,
    insurance_name: "IT Asset Insurance",
    insurance_coverage:
      "Technology-specific coverage with rapid replacement services",
    insurance_date_from: new Date("2024-06-01"), // Fix: Convert to Date object
    insurance_date_to: new Date("2025-05-31"),   // Fix: Convert to Date object
  },
  {
    insurance_id: 8,
    insurance_name: "Universal Business Cover",
    insurance_coverage:
      "All-risk coverage for business assets including natural disasters and cyber incidents",
    insurance_date_from: new Date("2024-07-01"), // Fix: Convert to Date object
    insurance_date_to: new Date("2025-06-30"),   // Fix: Convert to Date object
  },
];

export const status = [
  {
    status_id: 1,
    status_name: "Available",
  },
  {
    status_id: 2,
    status_name: "In Use",
  },
  {
    status_id: 3,
    status_name: "Under Repair",
  },
  {
    status_id: 4,
    status_name: "Out of Service",
  },
  {
    status_id: 5,
    status_name: "Borrowed",
  },
  {
    status_id: 6,
    status_name: "Reserved",
  },
  {
    status_id: 7,
    status_name: "Pending Return",
  },
  {
    status_id: 8,
    status_name: "Maintenance",
  },
  {
    status_id: 9,
    status_name: "Disposed",
  },
  {
    status_id: 10,
    status_name: "Lost",
  },
  {
    status_id: 11,
    status_name: "Stolen",
  },
  {
    status_id: 12,
    status_name: "Retired",
  },
];

export const company: Company[] = [
  {
    company_id: 1,
    name: "United Neon Advertising, Inc.",
    alias: "UNAI",
  },
  {
    company_id: 2,
    name: "Breakthrough Leadership Management Consultancy, In",
    alias: "BLMCI",
  },
  {
    company_id: 3,
    name: "InnovationOne Inc.",
    alias: "IOI",
  },
  {
    company_id: 4,
    name: "Inspire Leadership Consultancy Inc.",
    alias: "ILCI",
  },
  {
    company_id: 8,
    name: "SeeWorthy International/LinkOD",
    alias: "SeeWorthy",
  },
  {
    company_id: 9,
    name: "TapAds Media Corp",
    alias: "TAMC",
  },
  {
    company_id: 10,
    name: "United Neon Foundation Inc.",
    alias: "UNFI",
  },
  {
    company_id: 11,
    name: "United Transit Ads System Inc.",
    alias: "UTASI",
  },
  {
    company_id: 12,
    name: "Lighthouse Education Center",
    alias: "LEC",
  },
  {
    company_id: 13,
    name: "Ever Corporation",
    alias: "EVER",
  },
  {
    company_id: 14,
    name: "Gateway Bizads Inc.",
    alias: "GBI",
  },
];

// Fixed: Added company_id to match DepartmentSchema
export const departments: Department[] = [
  {
    department_id: 1,
    name: "Executive Office",
    alias: "EO",
    company_id: 1,
  },
  {
    department_id: 2,
    name: "Administrative Department",
    alias: "Admin",
    company_id: 1,
  },
  {
    department_id: 3,
    name: "Finance and Accounting",
    alias: "Finance",
    company_id: 1,
  },
  {
    department_id: 4,
    name: "OOH Creatives",
    alias: "Creatives",
    company_id: 1,
  },
  {
    department_id: 5,
    name: "People Operations and Culture Department",
    alias: "POCD",
    company_id: 1,
  },
  {
    department_id: 6,
    name: "Information Systems and Technology Integration",
    alias: "ISTI",
    company_id: 1,
  },
  {
    department_id: 7,
    name: "Project Compliance and Property Management",
    alias: "PCPM",
    company_id: 1,
  },
  {
    department_id: 8,
    name: "Corporate Relationship and Networking Management",
    alias: "",
    company_id: 1,
  },
  {
    department_id: 9,
    name: "Sales and Account Management",
    alias: "Sales",
    company_id: 1,
  },
  {
    department_id: 10,
    name: "Site Operations",
    alias: "Ops",
    company_id: 1,
  },
  {
    department_id: 11,
    name: "Vismin Operations",
    alias: "Vismin Ops",
    company_id: 1,
  },
  {
    department_id: 12,
    name: "Media Display Solutions",
    alias: "MDS",
    company_id: 13,
  },
  {
    department_id: 13,
    name: "Onion Bulb Production",
    alias: "OBP",
    company_id: 13,
  },
  {
    department_id: 14,
    name: "Plus Media",
    alias: "Plus",
    company_id: 13,
  },
  {
    department_id: 15,
    name: "Operations",
    alias: "TAMC Ops",
    company_id: 9,
  },
  {
    department_id: 16,
    name: "Scholar Management",
    alias: "Scholar",
    company_id: 10,
  },
  {
    department_id: 17,
    name: "Sales",
    alias: "TAMC Sales",
    company_id: 9,
  },
  {
    department_id: 18,
    name: "Sales",
    alias: "UTASI Sales",
    company_id: 11,
  },
  {
    department_id: 19,
    name: "ALS Management",
    alias: "ALS",
    company_id: 10,
  },
  {
    department_id: 20,
    name: "Office of the Chief Revenue Officer",
    alias: "Office of CRO",
    company_id: 1,
  },
  {
    department_id: 21,
    name: "Accounts Management",
    alias: "IOI Accounts Management",
    company_id: 3,
  },
  {
    department_id: 25,
    name: "Operations",
    alias: "UTASI Ops",
    company_id: 11,
  },
  {
    department_id: 26,
    name: "Creatives",
    alias: "IOI Creatives",
    company_id: 3,
  },
  {
    department_id: 27,
    name: "Executive Office",
    alias: "TAMC EO",
    company_id: 9,
  },
  {
    department_id: 28,
    name: "Administrative Office",
    alias: "UNFI Admin",
    company_id: 10,
  },
  {
    department_id: 29,
    name: "Executive Office",
    alias: "IOI EO",
    company_id: 3,
  },
  {
    department_id: 30,
    name: "Board of Directors",
    alias: "Board",
    company_id: 1,
  },
];

// NEW: Added units array to match UnitSchema
export const units: Unit[] = [
  {
    unit_id: 1,
    name: "Affiliates Finance and Accounting",
    alias: "Affi",
    company_id: 1,
    department_id: 3,
  },
  {
    unit_id: 2,
    name: "Billing and Collection Unit",
    alias: "AR",
    company_id: 1,
    department_id: 3,
  },
  {
    unit_id: 3,
    name: "UNAI Finance and Accounting",
    alias: "AP",
    company_id: 1,
    department_id: 3,
  },
  {
    unit_id: 4,
    name: "Building Admin",
    alias: null,
    company_id: 1,
    department_id: 2,
  },
  {
    unit_id: 5,
    name: "Logistics",
    alias: null,
    company_id: 1,
    department_id: 2,
  },
  {
    unit_id: 6,
    name: "Office Admin",
    alias: null,
    company_id: 1,
    department_id: 2,
  },
  {
    unit_id: 7,
    name: "Procurement",
    alias: null,
    company_id: 1,
    department_id: 2,
  },
  {
    unit_id: 8,
    name: "Warehouse",
    alias: null,
    company_id: 1,
    department_id: 2,
  },
  {
    unit_id: 9,
    name: "LED Tech Support",
    alias: null,
    company_id: 13,
    department_id: 12,
  },
  {
    unit_id: 10,
    name: "MDS Products",
    alias: null,
    company_id: 13,
    department_id: 12,
  },
  {
    unit_id: 11,
    name: "Art Production",
    alias: null,
    company_id: 1,
    department_id: 4,
  },
  {
    unit_id: 12,
    name: "Creatives",
    alias: null,
    company_id: 1,
    department_id: 4,
  },
  {
    unit_id: 29,
    name: "People Development",
    alias: null,
    company_id: 1,
    department_id: 5,
  },
  {
    unit_id: 30,
    name: "People Operations",
    alias: null,
    company_id: 1,
    department_id: 5,
  },
  {
    unit_id: 31,
    name: "Sales Unit 1",
    alias: "SU1",
    company_id: 1,
    department_id: 9,
  },
  {
    unit_id: 32,
    name: "Sales Unit 2",
    alias: "SU2",
    company_id: 1,
    department_id: 9,
  },
  {
    unit_id: 33,
    name: "Sales Unit 3",
    alias: "SU3",
    company_id: 1,
    department_id: 9,
  },
  {
    unit_id: 34,
    name: "Sales Unit 4",
    alias: "SU4",
    company_id: 1,
    department_id: 9,
  },
  {
    unit_id: 35,
    name: "Sales Unit 5",
    alias: "SU5",
    company_id: 1,
    department_id: 9,
  },
  {
    unit_id: 36,
    name: "Sales Unit 6",
    alias: "SU6",
    company_id: 1,
    department_id: 9,
  },
  {
    unit_id: 37,
    name: "Sales Unit 7",
    alias: "SU7",
    company_id: 1,
    department_id: 9,
  },
  {
    unit_id: 38,
    name: "Site Management",
    alias: null,
    company_id: 1,
    department_id: 10,
  },
  {
    unit_id: 39,
    name: "Site Logistics",
    alias: null,
    company_id: 1,
    department_id: 10,
  },
  {
    unit_id: 40,
    name: "Cebu Unit",
    alias: null,
    company_id: 1,
    department_id: 11,
  },
  {
    unit_id: 41,
    name: "Davao Unit",
    alias: null,
    company_id: 1,
    department_id: 11,
  },
  {
    unit_id: 44,
    name: "Support",
    alias: null,
    company_id: 1,
    department_id: 6,
  },
  {
    unit_id: 45,
    name: "System Development",
    alias: null,
    company_id: 1,
    department_id: 6,
  },
  {
    unit_id: 46,
    name: "Operations",
    alias: "MDS Ops",
    company_id: 13,
    department_id: 12,
  },
  {
    unit_id: 47,
    name: "Sales and Account",
    alias: "OBP Sales",
    company_id: 13,
    department_id: 13,
  },
  {
    unit_id: 48,
    name: "Administrative Support",
    alias: "OBP Admin",
    company_id: 13,
    department_id: 13,
  },
  {
    unit_id: 49,
    name: "Project Compliance",
    alias: null,
    company_id: 1,
    department_id: 7,
  },
  {
    unit_id: 51,
    name: "Administrative Office",
    alias: "MDS Admin",
    company_id: 13,
    department_id: 12,
  },
  {
    unit_id: 52,
    name: "Site Development 2",
    alias: null,
    company_id: 1,
    department_id: 10,
  },
  {
    unit_id: 53,
    name: "Executive Office",
    alias: "OBP EO",
    company_id: 13,
    department_id: 13,
  },
  {
    unit_id: 54,
    name: "Creatives",
    alias: "OBP Creatives",
    company_id: 13,
    department_id: 13,
  },
  {
    unit_id: 55,
    name: "Property Management",
    alias: null,
    company_id: 1,
    department_id: 7,
  },
  {
    unit_id: 56,
    name: "IBIDA Office",
    alias: "IBIDA",
    company_id: 13,
    department_id: 1,
  },
  {
    unit_id: 57,
    name: "Executive Committee",
    alias: "EXECOM",
    company_id: 13,
    department_id: 1,
  },
  {
    unit_id: 58,
    name: "Administration and SALT",
    alias: null,
    company_id: 13,
    department_id: 14,
  },
  {
    unit_id: 59,
    name: "Business Development",
    alias: "MDS BD",
    company_id: 13,
    department_id: 12,
  },
  {
    unit_id: 60,
    name: "Sales Support",
    alias: null,
    company_id: 1,
    department_id: 9,
  },
  {
    unit_id: 61,
    name: "Content and Communications",
    alias: null,
    company_id: 13,
    department_id: 13,
  },
  {
    unit_id: 62,
    name: "Site Development 1",
    alias: null,
    company_id: 1,
    department_id: 10,
  },
  {
    unit_id: 63,
    name: "Productions",
    alias: "OBP Prod",
    company_id: 13,
    department_id: 13,
  },
  {
    unit_id: 64,
    name: "Production and Content",
    alias: null,
    company_id: 13,
    department_id: 14,
  },
];

export const employees: Employee[] = [
  {
    user_id: 2,
    name: "Kimberly Ann Abucay",
    position: "Accounts Receivable Associate",
    company_id: 1,
    department_id: 3,
    unit_id: 1,
  },
  {
    user_id: 3,
    name: "Vincent Jay Abuhat",
    position: "Project Coordinator",
    company_id: 9,
    department_id: 15,
    unit_id: null,
  },
  {
    user_id: 4,
    name: "Brent Michael Acala",
    position: "Technical Support Associate",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 5,
    name: "Marie Faye Acupan",
    position: "Social Worker",
    company_id: 10,
    department_id: 16,
    unit_id: null,
  },
  {
    user_id: 6,
    name: "Trisha Mae Adao",
    position: "General Accounting Associate",
    company_id: 1,
    department_id: 3,
    unit_id: 1,
  },
  {
    user_id: 7,
    name: "Nicole Anne Admana",
    position: "HR Generalist",
    company_id: 1,
    department_id: null,
    unit_id: 30,
  },
  {
    user_id: 8,
    name: "Cristina Bianca Agravante",
    position: "CMS Specialist",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 9,
    name: "Saturnino Alavanzas",
    position: "Collector",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 10,
    name: "Ednalyn Alicaway",
    position: "Administrative Assistant",
    company_id: 9,
    department_id: 15,
    unit_id: null,
  },
  {
    user_id: 11,
    name: "Alpha Gracias Allanigui",
    position: "Chief Relationship Officer",
    company_id: 1,
    department_id: 1,
    unit_id: null,
  },
  {
    user_id: 12,
    name: "Dianne Clarisse Almazan",
    position: "Senior Sales Specialist",
    company_id: 9,
    department_id: 17,
    unit_id: null,
  },
  {
    user_id: 13,
    name: "John Andrew Ambrosio",
    position: "UTASI Sales Unit Head",
    company_id: 11,
    department_id: 18,
    unit_id: null,
  },
  {
    user_id: 14,
    name: "Joanna Cheewone Andaya",
    position: "OOH Media Associate",
    company_id: 1,
    department_id: 9,
    unit_id: 33,
  },
  {
    user_id: 15,
    name: "Noel Eric Ang",
    position: "Integrative Creative OOH Solutions Head",
    company_id: 1,
    department_id: 4,
    unit_id: 12,
  },
  {
    user_id: 16,
    name: "Angela Camila Antonio",
    position: "OOH Media Specialist",
    company_id: 1,
    department_id: 9,
    unit_id: 35,
  },
  {
    user_id: 17,
    name: "Charise Anne Apostol",
    position: "Assistant Sales Unit Head",
    company_id: 1,
    department_id: 9,
    unit_id: 31,
  },
  {
    user_id: 18,
    name: "Josephine Aquino",
    position: "Finance Account Specialist",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 19,
    name: "Joanne Arangorin",
    position: "Accounts Receivable Analyst",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 20,
    name: "Jian Patricia Aranjuez",
    position: "Office Admin And Procurement Coordinator",
    company_id: 1,
    department_id: 2,
    unit_id: 6,
  },
  {
    user_id: 21,
    name: "Joel Bacalla",
    position: "Administrative And Liaison Associate",
    company_id: 1,
    department_id: 3,
    unit_id: 1,
  },
  {
    user_id: 22,
    name: "Fritz Barfield",
    position: "Building Maintenance Specialist",
    company_id: 1,
    department_id: 2,
    unit_id: 4,
  },
  {
    user_id: 23,
    name: "Pablo Barrientos",
    position: "Tap Operations Coordinator",
    company_id: 9,
    department_id: 15,
    unit_id: null,
  },
  {
    user_id: 24,
    name: "Almond Jane Batobalonos",
    position: "Accounts Specialist",
    company_id: 13,
    department_id: 13,
    unit_id: 47,
  },
  {
    user_id: 25,
    name: "Rosendo Bautista",
    position: "Business Development Officer",
    company_id: 1,
    department_id: 20,
    unit_id: null,
  },
  {
    user_id: 26,
    name: "Alexandra Bernabe",
    position: "UI Designer",
    company_id: 1,
    department_id: 6,
    unit_id: 45,
  },
  {
    user_id: 27,
    name: "Melissa Billante",
    position: "Finance-Affiliates Supervisor",
    company_id: 1,
    department_id: 3,
    unit_id: 1,
  },
  {
    user_id: 28,
    name: "Kurt Symuon Boquiren",
    position: "Marketing Associate",
    company_id: 2,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 29,
    name: "Jovy Borabo",
    position: "Administrative Assistant",
    company_id: 13,
    department_id: 13,
    unit_id: 48,
  },
  {
    user_id: 30,
    name: "Lohkea Boribor",
    position: "ALS Instructional Manager",
    company_id: 10,
    department_id: 19,
    unit_id: null,
  },
  {
    user_id: 31,
    name: "Erwin Bunag",
    position: "Project Compliance And Property Management Head",
    company_id: 1,
    department_id: 7,
    unit_id: null,
  },
  {
    user_id: 32,
    name: "Margie Cabahug",
    position: "Business Development Associate",
    company_id: 1,
    department_id: 11,
    unit_id: 41,
  },
  {
    user_id: 33,
    name: "Noel Cabanilla",
    position: "Collector",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 34,
    name: "Jenie Calimpusan",
    position: "Assistant Civil Engineer",
    company_id: 1,
    department_id: 7,
    unit_id: 49,
  },
  {
    user_id: 35,
    name: "Earle Jan Capitan",
    position: "OOH Media Specialist",
    company_id: 1,
    department_id: 9,
    unit_id: 32,
  },
  {
    user_id: 36,
    name: "Maria Karen Joy Caramoan",
    position: "Head of Learning Operations",
    company_id: 8,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 37,
    name: "Jenemar Cascara",
    position: "Technical Engineer Associate",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 38,
    name: "Rosemir Castaneda",
    position: "Controller",
    company_id: 1,
    department_id: 1,
    unit_id: null,
  },
  {
    user_id: 39,
    name: "Jollina Nauline Castillo",
    position: "Digital Account Specialist",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 40,
    name: "Mac Summer Castillo",
    position: "Fleet Coordinator",
    company_id: 1,
    department_id: 2,
    unit_id: 5,
  },
  {
    user_id: 41,
    name: "Marylene Castillo",
    position: "General Accounting Specialist",
    company_id: 1,
    department_id: 3,
    unit_id: 1,
  },
  {
    user_id: 42,
    name: "Liberty Castillon",
    position: "Sales Unit Head",
    company_id: 1,
    department_id: 9,
    unit_id: 31,
  },
  {
    user_id: 43,
    name: "Viel Marie Castro",
    position: "Business Development Associate",
    company_id: 4,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 44,
    name: "Clark David Catipay",
    position: "Operations Specialist",
    company_id: 1,
    department_id: 11,
    unit_id: 40,
  },
  {
    user_id: 45,
    name: "Elaiza Cayetano",
    position: "Administrative Assistant",
    company_id: 13,
    department_id: 12,
    unit_id: 51,
  },
  {
    user_id: 46,
    name: "Francis Ceruma",
    position: "Senior Accounts Manager",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 47,
    name: "Philbert Chua",
    position: "Transit Ads Operations Head",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 48,
    name: "Amy Cichon",
    position: "Senior Site Specialist",
    company_id: 1,
    department_id: 10,
    unit_id: 52,
  },
  {
    user_id: 49,
    name: "Unica Coloquio",
    position: "Operation Support Officer",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 50,
    name: "Andrei Consuelo",
    position: "Multimedia Artist",
    company_id: 1,
    department_id: 4,
    unit_id: 11,
  },
  {
    user_id: 51,
    name: "Emeelisa Corpus",
    position: "Sales Unit Head",
    company_id: 1,
    department_id: 9,
    unit_id: 32,
  },
  {
    user_id: 52,
    name: "Charlotte Crisostomo",
    position: "Accounts Specialist",
    company_id: 1,
    department_id: 20,
    unit_id: null,
  },
  {
    user_id: 53,
    name: "John Cris Cruz",
    position: "Technical Support Engineer",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 54,
    name: "Beatrice Anne Del Rosario",
    position: "Recruitment Specialist",
    company_id: 1,
    department_id: null,
    unit_id: 30,
  },
  {
    user_id: 55,
    name: "Manuel Geon Dela Cruz",
    position: "Social Media Management Associate",
    company_id: 3,
    department_id: 26,
    unit_id: null,
  },
  {
    user_id: 56,
    name: "Ailene Dela Pena",
    position: "Junior Account Manager",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 57,
    name: "Analyn Dela Pena",
    position: "Deputy Head, Finance Services Senior Consultant",
    company_id: 1,
    department_id: 3,
    unit_id: 3,
  },
  {
    user_id: 58,
    name: "Florlynn Dela Pena",
    position: "Director For Business Partnerships",
    company_id: 4,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 59,
    name: "Lean Miguel Delica",
    position: "Administrative Assistant",
    company_id: 4,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 60,
    name: "Dianne Delos Reyes",
    position: "Compensation And Benefits Specialist",
    company_id: 1,
    department_id: null,
    unit_id: 30,
  },
  {
    user_id: 61,
    name: "Mynah Roa Destura",
    position: "Sales Unit Head",
    company_id: 1,
    department_id: 9,
    unit_id: 36,
  },
  {
    user_id: 62,
    name: "Jessa Dillera",
    position: "Business Development Consultant",
    company_id: 1,
    department_id: 11,
    unit_id: 41,
  },
  {
    user_id: 63,
    name: "Erickson Dino",
    position: "Chief Executive Officer",
    company_id: 9,
    department_id: 27,
    unit_id: null,
  },
  {
    user_id: 64,
    name: "Marjorie Dizon",
    position: "OOH Media Associate",
    company_id: 1,
    department_id: 9,
    unit_id: 31,
  },
  {
    user_id: 65,
    name: "Ferlie Dolar",
    position: "Sales Information Officer",
    company_id: 1,
    department_id: 9,
    unit_id: null,
  },
  {
    user_id: 66,
    name: "Alexander Dongaban",
    position: "Senior Digital Sales Specialist",
    company_id: 9,
    department_id: 17,
    unit_id: null,
  },
  {
    user_id: 67,
    name: "Shaira Angelica Escosia",
    position: "Senior Accounts Manager",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 68,
    name: "Honilyn Kae Esquivel",
    position: "Multimedia Artist",
    company_id: 9,
    department_id: 15,
    unit_id: null,
  },
  {
    user_id: 69,
    name: "Carlo Evangelista",
    position: "Marketing And Sales Activation Head",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 70,
    name: "Kristel Evangelista",
    position: "Logistics Associate",
    company_id: 1,
    department_id: 10,
    unit_id: 5,
  },
  {
    user_id: 71,
    name: "Mia Marie Fellizar",
    position: "OOH Media Specialist",
    company_id: 1,
    department_id: 9,
    unit_id: 32,
  },
  {
    user_id: 72,
    name: "Norman Ferrer",
    position: "Structural Engineer",
    company_id: 1,
    department_id: 7,
    unit_id: 49,
  },
  {
    user_id: 73,
    name: "Dennis Robert Ferriol",
    position: "Chief Revenue Officer",
    company_id: 1,
    department_id: 20,
    unit_id: null,
  },
  {
    user_id: 74,
    name: "Judith Flancia",
    position: "ALS Instructional Manager",
    company_id: 10,
    department_id: 19,
    unit_id: null,
  },
  {
    user_id: 75,
    name: "Gloria Flores",
    position: "General Accounting Consultant - Treasury Officer",
    company_id: 1,
    department_id: 3,
    unit_id: 3,
  },
  {
    user_id: 76,
    name: "Czarika Ann Francisco",
    position: "OOH Media Specialist",
    company_id: 1,
    department_id: 9,
    unit_id: 34,
  },
  {
    user_id: 77,
    name: "Donna Mae Fuentes",
    position: "Sales Unit Head",
    company_id: 1,
    department_id: 9,
    unit_id: 35,
  },
  {
    user_id: 78,
    name: "Renniel Lester Galang",
    position: "Junior Multimedia Artist",
    company_id: 3,
    department_id: 26,
    unit_id: null,
  },
  {
    user_id: 79,
    name: "Roderick Galang",
    position: "Site Inspector",
    company_id: 1,
    department_id: 10,
    unit_id: 5,
  },
  {
    user_id: 80,
    name: "Alfonso Galguerra",
    position: "Project Coordinator",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 81,
    name: "Arianne Camille Garcia",
    position: "Ooh Media Specialist",
    company_id: 1,
    department_id: 9,
    unit_id: 36,
  },
  {
    user_id: 82,
    name: "Sheryl Ehmene Garcia",
    position: "Sales Unit Head",
    company_id: 1,
    department_id: 9,
    unit_id: 34,
  },
  {
    user_id: 83,
    name: "Jeshua Immanuel Gay",
    position: "Senior Accounts Manager",
    company_id: 11,
    department_id: 18,
    unit_id: null,
  },
  {
    user_id: 84,
    name: "Sarah Joyce Gonzales",
    position: "Junior Multimedia Artist",
    company_id: 3,
    department_id: 26,
    unit_id: null,
  },
  {
    user_id: 85,
    name: "Rica Vanessa Gray",
    position: "Occupational Health Nurse",
    company_id: 1,
    department_id: null,
    unit_id: 29,
  },
  {
    user_id: 86,
    name: "Cris Grefaldo",
    position: "Electrical Engineer",
    company_id: 1,
    department_id: 7,
    unit_id: 49,
  },
  {
    user_id: 87,
    name: "Michiko Akira Gregorio",
    position: "Executive Producer",
    company_id: 13,
    department_id: 13,
    unit_id: 53,
  },
  {
    user_id: 88,
    name: "Reina Eloisa Hernandez",
    position: "Account Manager",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 89,
    name: "Vanessa Hernandez",
    position: "Accounting Officer",
    company_id: 1,
    department_id: 3,
    unit_id: 3,
  },
  {
    user_id: 90,
    name: "Meryll Hiponia",
    position: "OOH Media Specialist",
    company_id: 1,
    department_id: 9,
    unit_id: 32,
  },
  {
    user_id: 91,
    name: "Maria Genesis Hiso-An - Salvoro",
    position: "Senior Digital Marketing Copywriter",
    company_id: 3,
    department_id: 26,
    unit_id: null,
  },
  {
    user_id: 92,
    name: "Azriela Dayne Igno",
    position: "Multimedia Artist",
    company_id: 13,
    department_id: 13,
    unit_id: 54,
  },
  {
    user_id: 93,
    name: "Enrico Joaquin",
    position: "President",
    company_id: 2,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 94,
    name: "April Lagasca",
    position: "Business Development Associate",
    company_id: 1,
    department_id: 11,
    unit_id: 40,
  },
  {
    user_id: 95,
    name: "Jessa Laguitan",
    position: "Office Coordinator",
    company_id: 14,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 96,
    name: "Guilliano Nicco Lalimarmo",
    position: "Graphic Artist",
    company_id: 3,
    department_id: 26,
    unit_id: null,
  },
  {
    user_id: 97,
    name: "Jequo Paulo Lampa",
    position: "Property Management Assistant",
    company_id: 1,
    department_id: 7,
    unit_id: 55,
  },
  {
    user_id: 98,
    name: "Raphael Layosa",
    position: "Managing Director",
    company_id: 3,
    department_id: 29,
    unit_id: null,
  },
  {
    user_id: 99,
    name: "Zhyrell Joseph Leonardo",
    position: "Junior Creatives - Art",
    company_id: 1,
    department_id: 4,
    unit_id: 12,
  },
  {
    user_id: 100,
    name: "Flordeliz Leviste",
    position: "Accounting Specialist",
    company_id: 1,
    department_id: 3,
    unit_id: 3,
  },
  {
    user_id: 101,
    name: "Christopher Leynes",
    position: "IT Specialist - External",
    company_id: 1,
    department_id: 6,
    unit_id: 44,
  },
  {
    user_id: 102,
    name: "Ana Mae Libot",
    position: "Junior Account Manager",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 103,
    name: "Abigail Marie Lim",
    position: "Ibida Officer",
    company_id: 13,
    department_id: 1,
    unit_id: 56,
  },
  {
    user_id: 104,
    name: "Benjamin Ernest Lim",
    position: "Deputy COO",
    company_id: 13,
    department_id: 1,
    unit_id: 57,
  },
  {
    user_id: 105,
    name: "Daniel Christopher Lim",
    position: "CEO/Managing Director",
    company_id: 1,
    department_id: 30,
    unit_id: null,
  },
  {
    user_id: 106,
    name: "Epifania Lim",
    position: "Executive Director",
    company_id: 10,
    department_id: 28,
    unit_id: null,
  },
  {
    user_id: 107,
    name: "Jobert Lim",
    position: "Senior IT Specialist",
    company_id: 1,
    department_id: 6,
    unit_id: 44,
  },
  {
    user_id: 108,
    name: "Michael Kenneth Lim",
    position: "President",
    company_id: 1,
    department_id: 30,
    unit_id: null,
  },
  {
    user_id: 109,
    name: "Nathalie Lim",
    position: "Chief Finance Officer",
    company_id: 13,
    department_id: 1,
    unit_id: 57,
  },
  {
    user_id: 110,
    name: "Danrie Lineses",
    position: "Production And Content Creation Head",
    company_id: 13,
    department_id: 1,
    unit_id: 57,
  },
  {
    user_id: 111,
    name: "Gethsemanie Lineses",
    position: "Administrative And Talent Management Head",
    company_id: 13,
    department_id: 14,
    unit_id: 58,
  },
  {
    user_id: 112,
    name: "Geremy Lintag",
    position: "Technical Engineer Associate",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 113,
    name: "Myra Pauline Lirio",
    position: "Solutions Engineer",
    company_id: 13,
    department_id: 12,
    unit_id: 59,
  },
  {
    user_id: 114,
    name: "Ralph Johnedel Lirio",
    position: "Technical Support Engineer",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 115,
    name: "Maria Elaine Liwag",
    position: "Sales Support Specialist - Sales Services Officer",
    company_id: 1,
    department_id: 9,
    unit_id: 60,
  },
  {
    user_id: 116,
    name: "Michael Lontoc",
    position: "Technical Support Engineer",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 117,
    name: "Maria Annika Lopez",
    position: "Creative Director",
    company_id: 3,
    department_id: 26,
    unit_id: null,
  },
  {
    user_id: 118,
    name: "Rafael Antonio Lopez",
    position: "Multimedia Art Supervisor",
    company_id: 1,
    department_id: 4,
    unit_id: 11,
  },
  {
    user_id: 119,
    name: "Jerbey Luangco",
    position: "BD Visayas Unit Head",
    company_id: 1,
    department_id: 11,
    unit_id: 40,
  },
  {
    user_id: 120,
    name: "Maricar Maala",
    position: "Logistic Specialist",
    company_id: 1,
    department_id: 10,
    unit_id: 5,
  },
  {
    user_id: 121,
    name: "Philip Nerius Mabilin",
    position: "Technical Support Associate",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 122,
    name: "Katherine Maglaque",
    position: "Executive Assistant to The Finance Controller",
    company_id: 1,
    department_id: 1,
    unit_id: null,
  },
  {
    user_id: 123,
    name: "Anthony Malanco",
    position: "Project Coordinator",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 124,
    name: "Rovie Kathleen Manabat",
    position: "Creative Director",
    company_id: 13,
    department_id: 13,
    unit_id: 54,
  },
  {
    user_id: 125,
    name: "Dave Mark Manalo",
    position: "MDS Operations Head",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 126,
    name: "Lyka Mae Manalo",
    position: "Admin Service Support",
    company_id: 1,
    department_id: 2,
    unit_id: 4,
  },
  {
    user_id: 127,
    name: "Maricar Mandique",
    position: "Accounts Receivable Analyst",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 128,
    name: "Jeffrey Manhilot",
    position: "President",
    company_id: 4,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 129,
    name: "Luis Gian Paolo Mapa",
    position: "Inspire General Manager",
    company_id: 8,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 130,
    name: "Diane Paulyn Marqueses",
    position: "Graphic Artist",
    company_id: 3,
    department_id: 26,
    unit_id: null,
  },
  {
    user_id: 131,
    name: "Johnden Medina",
    position: "Creative Writer",
    company_id: 13,
    department_id: 13,
    unit_id: 61,
  },
  {
    user_id: 132,
    name: "Cae Ann Mendoza",
    position: "Admin and Social Media Associate",
    company_id: 12,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 133,
    name: "Michael San Mendoza",
    position: "OOH Sales Department Head",
    company_id: 1,
    department_id: 9,
    unit_id: null,
  },
  {
    user_id: 134,
    name: "Rey Magno Mendoza",
    position: "Learning And Development Consultant",
    company_id: 13,
    department_id: 1,
    unit_id: 57,
  },
  {
    user_id: 135,
    name: "Chancellor Miro",
    position: "Business Development Specialist",
    company_id: 1,
    department_id: 11,
    unit_id: 40,
  },
  {
    user_id: 136,
    name: "Juan Miguel Mojica",
    position: "Logistics Office Associate",
    company_id: 1,
    department_id: 10,
    unit_id: 5,
  },
  {
    user_id: 137,
    name: "Carlo Inigo Montano",
    position: "Administrative Officer",
    company_id: 8,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 138,
    name: "Jason Montemayor",
    position: "Technical Support Specialist",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 139,
    name: "Monica Montero",
    position: "Administrative Specialist",
    company_id: 9,
    department_id: 15,
    unit_id: null,
  },
  {
    user_id: 140,
    name: "Rex David Morales",
    position: "Business Development Associate",
    company_id: 2,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 141,
    name: "Franco Louis Morante",
    position: "Junior Creatives - Art",
    company_id: 1,
    department_id: 4,
    unit_id: 12,
  },
  {
    user_id: 142,
    name: "Cyrhine Moros",
    position: "Operation Support Associate",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 143,
    name: "Ranniah Naseef",
    position: "Multimedia Artist",
    company_id: 13,
    department_id: 13,
    unit_id: 54,
  },
  {
    user_id: 144,
    name: "Mary Drew Nieva",
    position: "Account Manager",
    company_id: 11,
    department_id: 18,
    unit_id: null,
  },
  {
    user_id: 145,
    name: "Adolfo Norcio",
    position: "Senior Site Inspector",
    company_id: 1,
    department_id: 10,
    unit_id: 5,
  },
  {
    user_id: 146,
    name: "Alexa Jean Obmerga",
    position: "Operations Specialist",
    company_id: 9,
    department_id: 15,
    unit_id: null,
  },
  {
    user_id: 147,
    name: "Gene Olojan",
    position: "Vismin Operations Head",
    company_id: 1,
    department_id: 11,
    unit_id: 41,
  },
  {
    user_id: 148,
    name: "Deljean Orpilla",
    position: "Business Development Officer",
    company_id: 2,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 149,
    name: "Leila Ortiz Luis",
    position: "Executive Assistant",
    company_id: 1,
    department_id: 1,
    unit_id: null,
  },
  {
    user_id: 150,
    name: "Fair Ortiz",
    position: "OOH Site Operations Head",
    company_id: 1,
    department_id: 10,
    unit_id: null,
  },
  {
    user_id: 151,
    name: "Lenie Pagdanganan",
    position: "Billing & Collection Team Head",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 152,
    name: "Linbert Parreno",
    position: "Project Coordinator",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 153,
    name: "Joan Pasigado",
    position: "Deputy Head For Finance Affiliates",
    company_id: 1,
    department_id: 3,
    unit_id: 1,
  },
  {
    user_id: 154,
    name: "Bennes Patio",
    position: "Production Art Director",
    company_id: 1,
    department_id: 4,
    unit_id: 11,
  },
  {
    user_id: 155,
    name: "John Mark Pazcoguin",
    position: "Media Management Documentation Specialist",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 156,
    name: "Ma. Eliza Pena",
    position: "Sales Admin Associate",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 157,
    name: "Norvin Kyle Perez",
    position: "Web Developer",
    company_id: 1,
    department_id: 6,
    unit_id: 45,
  },
  {
    user_id: 158,
    name: "Rizza Pineda",
    position: "General Accounting Associate",
    company_id: 1,
    department_id: 3,
    unit_id: 3,
  },
  {
    user_id: 159,
    name: "Edgar Puruganan",
    position: "Warehouse Specialist",
    company_id: 1,
    department_id: 2,
    unit_id: 8,
  },
  {
    user_id: 160,
    name: "Marygrace Ragamat",
    position: "Business Development Associate",
    company_id: 2,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 161,
    name: "Michael Ramilo",
    position: "Information Systems & Technology Integration Head",
    company_id: 1,
    department_id: 6,
    unit_id: null,
  },
  {
    user_id: 162,
    name: "Lorraine Ramos",
    position: "Web Developer",
    company_id: 1,
    department_id: 6,
    unit_id: 45,
  },
  {
    user_id: 163,
    name: "Rona-Rose Ramos",
    position: "Administrative Officer",
    company_id: 1,
    department_id: 1,
    unit_id: null,
  },
  {
    user_id: 164,
    name: "Jonamie Resuma",
    position: "Multimedia Artist",
    company_id: 1,
    department_id: 4,
    unit_id: 11,
  },
  {
    user_id: 165,
    name: "Jennielyn Reyes",
    position: "Site Specialist",
    company_id: 1,
    department_id: 10,
    unit_id: 62,
  },
  {
    user_id: 166,
    name: "Pablo Ricafort",
    position: "Motorized Accounts Receivable Representative",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 167,
    name: "Vincent Kyle Rinoza",
    position: "Web Developer",
    company_id: 1,
    department_id: 6,
    unit_id: 45,
  },
  {
    user_id: 168,
    name: "Lita Rivera",
    position: "Procurement Specialist",
    company_id: 1,
    department_id: 2,
    unit_id: 7,
  },
  {
    user_id: 169,
    name: "Ma. Gabrielle Rivera",
    position: "Graphic Artist",
    company_id: 1,
    department_id: 4,
    unit_id: 11,
  },
  {
    user_id: 170,
    name: "Ameer Rojo",
    position: "Web Developer",
    company_id: 1,
    department_id: 6,
    unit_id: 45,
  },
  {
    user_id: 171,
    name: "Rho-V Anne Roque",
    position: "Sales Support Associate",
    company_id: 1,
    department_id: 9,
    unit_id: 60,
  },
  {
    user_id: 172,
    name: "James Arvin San Andres",
    position: "Media Production Specialist",
    company_id: 13,
    department_id: 13,
    unit_id: 63,
  },
  {
    user_id: 173,
    name: "Mary Megjunie San Andres",
    position: "Site Specialist",
    company_id: 1,
    department_id: 10,
    unit_id: 62,
  },
  {
    user_id: 174,
    name: "Ralph Jefferson San Jose",
    position: "Junior 3D Modeler",
    company_id: 13,
    department_id: 13,
    unit_id: 54,
  },
  {
    user_id: 175,
    name: "Francis Kenneth San Juan",
    position: "Junior Motion Graphics Designer",
    company_id: 13,
    department_id: 13,
    unit_id: 54,
  },
  {
    user_id: 176,
    name: "Pauline San Juan",
    position: "Admin Head",
    company_id: 1,
    department_id: 2,
    unit_id: null,
  },
  {
    user_id: 177,
    name: "Albert Santos",
    position: "Project Compliance Specialist",
    company_id: 1,
    department_id: 10,
    unit_id: 5,
  },
  {
    user_id: 178,
    name: "May Ann Santos",
    position: "Field Ops Specialist - Field Operations Officer",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 179,
    name: "Justin Sibulo",
    position: "Junior Multimedia Artist",
    company_id: 3,
    department_id: 26,
    unit_id: null,
  },
  {
    user_id: 180,
    name: "Jocelyn Sicena",
    position: "AR Admin & Finance Account Specialist",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 181,
    name: "Bridgette Margarette Solis",
    position: "Multimedia Artist",
    company_id: 13,
    department_id: 14,
    unit_id: 64,
  },
  {
    user_id: 182,
    name: "Deborah Sotomil",
    position: "OOH Media Specialist",
    company_id: 1,
    department_id: 9,
    unit_id: 34,
  },
  {
    user_id: 183,
    name: "Cheryl Faith Sta. Maria",
    position: "Project Compliance Head",
    company_id: 1,
    department_id: 7,
    unit_id: 49,
  },
  {
    user_id: 184,
    name: "Fredelito Suarez",
    position: "Chief People Officer",
    company_id: 13,
    department_id: 1,
    unit_id: 57,
  },
  {
    user_id: 185,
    name: "Christian Sucgang",
    position: "Sales Executive",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 186,
    name: "Aldin Sy",
    position: "Sales Unit Head",
    company_id: 1,
    department_id: 9,
    unit_id: 33,
  },
  {
    user_id: 187,
    name: "Juliandel Tabino",
    position: "People Management Head",
    company_id: 1,
    department_id: null,
    unit_id: 30,
  },
  {
    user_id: 188,
    name: "Rodolfo Tabuzo",
    position: "Project Coordinator",
    company_id: 11,
    department_id: 25,
    unit_id: null,
  },
  {
    user_id: 189,
    name: "Jerol Earl Tan",
    position: "Senior Sales Specialist",
    company_id: 9,
    department_id: 17,
    unit_id: null,
  },
  {
    user_id: 190,
    name: "Wency Adrielyne Tan",
    position: "Mds Business Unit Head",
    company_id: 13,
    department_id: 12,
    unit_id: 51,
  },
  {
    user_id: 191,
    name: "Maylyn Tanamor",
    position: "ALS Instructional Manager",
    company_id: 10,
    department_id: 19,
    unit_id: null,
  },
  {
    user_id: 192,
    name: "Djhoanna Dianne Tipan",
    position: "Account Manager",
    company_id: 11,
    department_id: 18,
    unit_id: null,
  },
  {
    user_id: 193,
    name: "Josephine Torrecampo",
    position: "Accounts Receivable Specialist",
    company_id: 1,
    department_id: 3,
    unit_id: 2,
  },
  {
    user_id: 194,
    name: "Mark Gerard Tubigan",
    position: "Programmer",
    company_id: 1,
    department_id: 1,
    unit_id: null,
  },
  {
    user_id: 195,
    name: "Christiane Turnos",
    position: "Senior Digital Sales Specialist",
    company_id: 9,
    department_id: 17,
    unit_id: null,
  },
  {
    user_id: 196,
    name: "Joemathel Ubarco",
    position: "Account Manager",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 197,
    name: "Marites Vigonte",
    position: "General Accounting Associate",
    company_id: 1,
    department_id: 3,
    unit_id: 3,
  },
  {
    user_id: 198,
    name: "Mark Alud Villamor",
    position: "Technical Support Specialist",
    company_id: 13,
    department_id: 12,
    unit_id: 46,
  },
  {
    user_id: 199,
    name: "Marlon Villanea",
    position: "Junior Account Manager",
    company_id: 3,
    department_id: 21,
    unit_id: null,
  },
  {
    user_id: 200,
    name: "Marybeth Villanueva",
    position: "Administrative Assistant",
    company_id: 1,
    department_id: 2,
    unit_id: 6,
  },
  {
    user_id: 201,
    name: "Pauline Grace Villanueva",
    position: "Tap Ads Operations Head",
    company_id: 9,
    department_id: 15,
    unit_id: null,
  },
  {
    user_id: 202,
    name: "Sherleen Mae Villanueva",
    position: "Site Specialist",
    company_id: 1,
    department_id: 10,
    unit_id: 52,
  },
  {
    user_id: 203,
    name: "Kristine Kae Viscayno",
    position: "Service Desk Officer",
    company_id: 8,
    department_id: null,
    unit_id: null,
  },
  {
    user_id: 204,
    name: "Xyza Mae Zamora",
    position: "Operations Specialist",
    company_id: 1,
    department_id: 11,
    unit_id: 41,
  },
];

export const urgency = [
  { urgency_id: 1, urgency_name: "Low" },
  { urgency_id: 2, urgency_name: "Medium" },
  { urgency_id: 3, urgency_name: "High" },
  { urgency_id: 4, urgency_name: "Critical" },
  { urgency_id: 5, urgency_name: "Emergency" },
];
